Document: vyatta-op-quagga
Title: Debian vyatta-op-quagga Manual
Author: <insert document author here>
Abstract: This manual describes what vyatta-op-quagga is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vyatta-op-quagga/vyatta-op-quagga.sgml.gz

Format: postscript
Files: /usr/share/doc/vyatta-op-quagga/vyatta-op-quagga.ps.gz

Format: text
Files: /usr/share/doc/vyatta-op-quagga/vyatta-op-quagga.text.gz

Format: HTML
Index: /usr/share/doc/vyatta-op-quagga/html/index.html
Files: /usr/share/doc/vyatta-op-quagga/html/*.html

  
